import Head from 'next/head';

import Form from '../components/Form';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [username, setUsername] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form username={username} onChange={handleChange} connect={connect} />
      </main>
    </div>
  );
}
